### ISSUE TITLE
Discuss the UI where loklak API would appear as an option 

### ISSUE THREAD

**Issue by sopu** [loklak/wp-twitter-widget#6]
Currently I have added the option in widgets appearance page. 
![selection_003](https://cloud.githubusercontent.com/assets/6399612/15800912/a3cb7f9c-2aa3-11e6-8bb2-2326c253d793.png)
Please suggest what else would be better.

**Comment by mariobehling** [comment]
These kind of options are usually in the Settings section.

**Comment by mariobehling** [comment]
Please add here
* [ ] "Use anonymous API of loklak.org"
![screenshot from 2016-06-05 14 11 59](https://cloud.githubusercontent.com/assets/1583873/15805357/f084cd14-2b27-11e6-84f1-d0212233a9d5.png)

**Comment by sopu** [comment]
@mariobehling I would also like to ask the creator of that plugin on how he wants the UI to be. 
I am putting this as a PR to the original repo.

**Comment by mariobehling** [comment]
@sopu We can discuss for a long time or get some code done. It is unsure, if the creator agrees at all with adding loklak and feedback might take a long time. Please let's progress and get some code done. It would be good to have loklak as a global option in the settings as well.

**Comment by sopu** [comment]
@mariobehling the settings page is rendered from a submodule (https://github.com/timwhitlock/wp-twitter-api/tree/9ddd9adc5fea2568b67d2e96326f4b2d7f847551). To add globally to settings page, we would have to tweak that submodule. And then connect it to the widget.

**Comment by mariobehling** [comment]
@sopu Yes, I know. Please proceed. We need this one or the other way. We could later also use that module without twitter. So we definitely need that part to get done.

**Comment by sopu** [comment]
The final UI as decided is 
![selection_005](https://cloud.githubusercontent.com/assets/6399612/15827184/1fa70ae8-2c28-11e6-9a63-1f138f263022.png)

**Comment by sopu** [comment]
Closing issue!
