### ISSUE TITLE
Deploy online to test

### ISSUE THREAD

**Issue by mariobehling** [loklak/wp-twitter-widget#9]
Would like to see implementation and if info on loklak.org with links has been added.

**Comment by sopu** [comment]
Please see somethingtothink.com . 
NOTE: Due to cloudflare-WP ssl issues, you might need to load unsafe scripts. 
![screenshot from 2016-06-09 16-32-52](https://cloud.githubusercontent.com/assets/6399612/15927498/c380a80c-2e5f-11e6-848b-61130d8ecf34.png)

**Comment by sopu** [comment]
Closing the issue!

**Comment by mariobehling** [comment]
There is a message "Error: Invalid or expired token."

Also the design is erroneous. Do you see that? Is that a deployment issue? If yes, please fix. If not close this issue and add a new issue and fix it.

**Comment by sopu** [comment]
The message is due to the fact that even when loklak option is authenticated, the twitter auth settings are being saved.

**Comment by sopu** [comment]
The design issue was caused by WP default settings styling. 
Closing this issue, adding new one. @mariobehling
